;spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO

info:
  app:
    name: Spring Boot 2 actuator Application

management:
  endpoints:
    web:
      exposure:
        include: info, health, release-notes


  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207